"""
core/alert_email.py — Email alerts for high-severity intrusion events.

Features:
  - SMTP with TLS (Gmail-compatible)
  - Per-IP throttling (don't spam for the same attacker)
  - HTML email template with alert details
  - Optional async sending (non-blocking)
"""

import sys
import os
import smtplib
import threading
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config
from core.logger import get_logger

log = get_logger("EmailAlert")

# Per-IP throttle: ip -> last_sent_timestamp
_throttle: dict = {}
_throttle_lock = threading.Lock()


def _should_send(ip: str) -> bool:
    now = time.time()
    with _throttle_lock:
        last = _throttle.get(ip, 0)
        if now - last < config.EMAIL_THROTTLE_SECONDS:
            return False
        _throttle[ip] = now
    return True


def _build_html(alert: dict) -> str:
    geo = alert.get("geo", {})
    details = alert.get("details", {})
    severity = alert.get("severity", "HIGH")
    color_map = {
        "CRITICAL": "#ff2d55",
        "HIGH": "#ff9f0a",
        "MEDIUM": "#30d158",
        "LOW": "#636366",
    }
    color = color_map.get(severity, "#ff9f0a")

    return f"""
    <html><body style="font-family:Arial,sans-serif;background:#1c1c1e;color:#f2f2f7;padding:20px;">
      <div style="max-width:600px;margin:auto;background:#2c2c2e;border-radius:12px;padding:24px;
                  border-top:4px solid {color};">
        <h2 style="color:{color};margin:0 0 16px;">
          🚨 IDS/IPS Alert — {alert.get('attack_type', 'Intrusion')}
        </h2>
        <table width="100%" cellpadding="8" style="border-collapse:collapse;">
          <tr><td style="color:#aeaeb2;">Timestamp</td>
              <td><b>{alert.get('timestamp','')}</b></td></tr>
          <tr><td style="color:#aeaeb2;">Source IP</td>
              <td><b style="color:{color};">{alert.get('src_ip','')}</b></td></tr>
          <tr><td style="color:#aeaeb2;">Attack Type</td>
              <td><b>{alert.get('attack_type','')}</b></td></tr>
          <tr><td style="color:#aeaeb2;">Severity</td>
              <td><b style="color:{color};">{severity}</b></td></tr>
          <tr><td style="color:#aeaeb2;">Threat Score</td>
              <td><b>{alert.get('threat_score',0):.1f} / 100</b></td></tr>
          <tr><td style="color:#aeaeb2;">Confidence</td>
              <td>{alert.get('confidence',0)*100:.1f}%</td></tr>
          <tr><td style="color:#aeaeb2;">Location</td>
              <td>{geo.get('city','?')}, {geo.get('country','?')}</td></tr>
          <tr><td style="color:#aeaeb2;">ISP</td>
              <td>{geo.get('isp','Unknown')}</td></tr>
        </table>
        <h3 style="color:#aeaeb2;margin:16px 0 8px;">Detection Details</h3>
        <pre style="background:#1c1c1e;border-radius:8px;padding:12px;font-size:12px;
                    color:#30d158;white-space:pre-wrap;">{details}</pre>
        <p style="margin-top:20px;color:#636366;font-size:12px;">
          This alert was generated by the AI-based IDS/IPS system.
          The attacker IP has been automatically blocked.
        </p>
      </div>
    </body></html>
    """


def send_alert_email(alert: dict):
    """Send an HTML email alert (blocking). Call from thread for async."""
    if not config.EMAIL_ENABLED:
        return

    ip = alert.get("src_ip", "unknown")
    if not _should_send(ip):
        log.debug(f"[EmailAlert] Throttled — skipping email for {ip}")
        return

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = (
            f"[IDS ALERT] {alert.get('severity','HIGH')} — "
            f"{alert.get('attack_type','Intrusion')} from {ip}"
        )
        msg["From"] = config.SMTP_USER
        msg["To"] = ", ".join(config.ALERT_RECIPIENTS)

        html_part = MIMEText(_build_html(alert), "html")
        msg.attach(html_part)

        with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(config.SMTP_USER, config.SMTP_PASSWORD)
            server.sendmail(
                config.SMTP_USER,
                config.ALERT_RECIPIENTS,
                msg.as_string()
            )

        log.info(f"[EmailAlert] Alert email sent for {ip}")
    except Exception as e:
        log.error(f"[EmailAlert] Failed to send email: {e}")


def send_alert_email_async(alert: dict):
    """Send email in a background thread (non-blocking)."""
    t = threading.Thread(target=send_alert_email, args=[alert], daemon=True)
    t.start()
